# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: false
  per_page: 3
  permalink: "/page/:num/"

comments: false

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jed Meier
description: "Jed Meier "
keywords: "Jed Meier, Jed, Meier, Des Moines, Software Engineer, blog, web"
url: https://jrmeier.github.io
# baseurl: "https://jedm.dev"
baseUrl: "http://localhost:4000"

google_analytics: G-01CEWEYG00
repo: http://github.com/jrmeier/jedmdev
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jed Meier
  job: Full-Stack Software Engineer
  bio: "Automate everything @<a href='https://denimsocial.com'>Denim Social</a>."
  thumb: /images/author.jpg
  email: mail@jedm.dev
  url: https://jedm.dev
  github: https://github.com/jrmeier
  # twitter: https://twitter.com/umdevux
  #facebook: https://facebook.com/umdevux
  linkedin: https://linkedin.com/in/jedrmeier

# navbar pages
navbar:
  - slug: resume
    title: Resume
  - slug: impossible-list
    title: Impossible List
  - slug: fast-trade
    title: Fast Trade

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]

#theme: jekyll-theme-cayman
