# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jed Meier
description: "Jed Meier "
keywords: "Jed Meier, Jed, Meier, Des Moines, Software Engineer, blog, web"
url: http://jedmeier.com
baseurl: ""

#google_analytics: UA-52446115-1
#repo: http://github.com/nandomoreirame/end2end
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jed Meier
  job: Full-Stack Engineer
  bio: "Effienct, sensible design, and always on the hunt for a new project. Currently at <a href='https://denimlabs.com'>Denim</a>."
  thumb: /images/author.jpg
  email: nandomoreira.me@gmail.com
  url: https://jedmeier.com
  github: https://github.com/jrmeier
  #twitter: https://twitter.com/umdevux
  #facebook: https://facebook.com/umdevux
  linkedin: https://linkedin.com/in/jedrmeier

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: impossible-list
    title: Impossible List

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
